// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiutqhikwjvcdwtulzwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppdXRxaGlrd2p2Y2R3dHVsendrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTc3MDMsImV4cCI6MjA2Njk3MzcwM30.i3T2HZ9rJh2mMxZyb8CFplHEYcI24jsDOApR3baETXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});